export {default as GithubIcon} from './Github.svg'
export {default as TwitterIcon} from './Twitter.svg';
export {default as MailIcon} from './Mail.svg';
export {default as HomeIcon} from './Home.svg'
export {default as TextIcon} from './FileText.svg'
export {default as ListIcon} from './List.svg'
export {default as TagIcon} from './Tag.svg';
export {default as NpmIcon} from './Npm.svg'
export {default as RSSIcon} from './Rss.svg';