// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Index$default(Props) {
  return React.createElement("div", undefined, React.createElement("h1", undefined, "Hello World"));
}

var $$default = Index$default;

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
